let cars = [
  {
    city_mpg: 22,
    class: "compact car",
    combination_mpg: 24,
    cylinders: 4,
    displacement: 1.6,
    drive: "fwd",
    fuel_type: "gas",
    highway_mpg: 27,
    make: "kia",
    model: "sephia",
    transmission: "a",
    year: 1994,
  },
  {
    city_mpg: 23,
    class: "compact car",
    combination_mpg: 26,
    cylinders: 4,
    displacement: 1.6,
    drive: "fwd",
    fuel_type: "gas",
    highway_mpg: 30,
    make: "kia",
    model: "sephia",
    transmission: "m",
    year: 1994,
  },
  {
    city_mpg: 22,
    class: "compact car",
    combination_mpg: 25,
    cylinders: 4,
    displacement: 1.6,
    drive: "fwd",
    fuel_type: "gas",
    highway_mpg: 31,
    make: "kia",
    model: "sephia",
    transmission: "a",
    year: 1995,
  },
  {
    city_mpg: 22,
    class: "compact car",
    combination_mpg: 25,
    cylinders: 4,
    displacement: 1.6,
    drive: "fwd",
    fuel_type: "gas",
    highway_mpg: 30,
    make: "kia",
    model: "sephia",
    transmission: "m",
    year: 1995,
  },
  {
    city_mpg: 25,
    class: "compact car",
    combination_mpg: 28,
    cylinders: 4,
    displacement: 1.6,
    drive: "fwd",
    fuel_type: "gas",
    highway_mpg: 32,
    make: "kia",
    model: "sephia",
    transmission: "m",
    year: 1995,
  },
  {
    city_mpg: 20,
    class: "compact car",
    combination_mpg: 22,
    cylinders: 4,
    displacement: 1.8,
    drive: "fwd",
    fuel_type: "gas",
    highway_mpg: 26,
    make: "kia",
    model: "sephia",
    transmission: "a",
    year: 1995,
  },
  {
    city_mpg: 21,
    class: "compact car",
    combination_mpg: 23,
    cylinders: 4,
    displacement: 1.8,
    drive: "fwd",
    fuel_type: "gas",
    highway_mpg: 26,
    make: "kia",
    model: "sephia",
    transmission: "m",
    year: 1995,
  },
  {
    city_mpg: 17,
    class: "special purpose vehicle",
    combination_mpg: 19,
    cylinders: 4,
    displacement: 2,
    drive: "rwd",
    fuel_type: "gas",
    highway_mpg: 21,
    make: "kia",
    model: "sportage 2wd",
    transmission: "m",
    year: 1995,
  },
  {
    city_mpg: 16,
    class: "special purpose vehicle",
    combination_mpg: 18,
    cylinders: 4,
    displacement: 2,
    drive: "awd",
    fuel_type: "gas",
    highway_mpg: 20,
    make: "kia",
    model: "sportage 4wd",
    transmission: "a",
    year: 1995,
  },
  {
    city_mpg: 18,
    class: "special purpose vehicle",
    combination_mpg: 19,
    cylinders: 4,
    displacement: 2,
    drive: "awd",
    fuel_type: "gas",
    highway_mpg: 22,
    make: "kia",
    model: "sportage 4wd",
    transmission: "m",
    year: 1995,
  },
];
let cars = [{"city_mpg":22,"class":"compact car","combination_mpg":24,"cylinders":4,"displacement":1.6,"drive":"fwd","fuel_type":"gas","highway_mpg":27,"make":"kia","model":"sephia","transmission":"a","year":1994},{"city_mpg":23,"class":"compact car","combination_mpg":26,"cylinders":4,"displacement":1.6,"drive":"fwd","fuel_type":"gas","highway_mpg":30,"make":"kia","model":"sephia","transmission":"m","year":1994},{"city_mpg":22,"class":"compact car","combination_mpg":25,"cylinders":4,"displacement":1.6,"drive":"fwd","fuel_type":"gas","highway_mpg":31,"make":"kia","model":"sephia","transmission":"a","year":1995},{"city_mpg":22,"class":"compact car","combination_mpg":25,"cylinders":4,"displacement":1.6,"drive":"fwd","fuel_type":"gas","highway_mpg":30,"make":"kia","model":"sephia","transmission":"m","year":1995},{"city_mpg":25,"class":"compact car","combination_mpg":28,"cylinders":4,"displacement":1.6,"drive":"fwd","fuel_type":"gas","highway_mpg":32,"make":"kia","model":"sephia","transmission":"m","year":1995},{"city_mpg":20,"class":"compact car","combination_mpg":22,"cylinders":4,"displacement":1.8,"drive":"fwd","fuel_type":"gas","highway_mpg":26,"make":"kia","model":"sephia","transmission":"a","year":1995},{"city_mpg":21,"class":"compact car","combination_mpg":23,"cylinders":4,"displacement":1.8,"drive":"fwd","fuel_type":"gas","highway_mpg":26,"make":"kia","model":"sephia","transmission":"m","year":1995},{"city_mpg":17,"class":"special purpose vehicle","combination_mpg":19,"cylinders":4,"displacement":2,"drive":"rwd","fuel_type":"gas","highway_mpg":21,"make":"kia","model":"sportage 2wd","transmission":"m","year":1995},{"city_mpg":16,"class":"special purpose vehicle","combination_mpg":18,"cylinders":4,"displacement":2,"drive":"awd","fuel_type":"gas","highway_mpg":20,"make":"kia","model":"sportage 4wd","transmission":"a","year":1995},{"city_mpg":18,"class":"special purpose vehicle","combination_mpg":19,"cylinders":4,"displacement":2,"drive":"awd","fuel_type":"gas","highway_mpg":22,"make":"kia","model":"sportage 4wd","transmission":"m","year":1995}]let cars = [{"city_mpg":22,"class":"compact car","combination_mpg":24,"cylinders":4,"displacement":1.6,"drive":"fwd","fuel_type":"gas","highway_mpg":27,"make":"kia","model":"sephia","transmission":"a","year":1994},{"city_mpg":23,"class":"compact car","combination_mpg":26,"cylinders":4,"displacement":1.6,"drive":"fwd","fuel_type":"gas","highway_mpg":30,"make":"kia","model":"sephia","transmission":"m","year":1994},{"city_mpg":22,"class":"compact car","combination_mpg":25,"cylinders":4,"displacement":1.6,"drive":"fwd","fuel_type":"gas","highway_mpg":31,"make":"kia","model":"sephia","transmission":"a","year":1995},{"city_mpg":22,"class":"compact car","combination_mpg":25,"cylinders":4,"displacement":1.6,"drive":"fwd","fuel_type":"gas","highway_mpg":30,"make":"kia","model":"sephia","transmission":"m","year":1995},{"city_mpg":25,"class":"compact car","combination_mpg":28,"cylinders":4,"displacement":1.6,"drive":"fwd","fuel_type":"gas","highway_mpg":32,"make":"kia","model":"sephia","transmission":"m","year":1995},{"city_mpg":20,"class":"compact car","combination_mpg":22,"cylinders":4,"displacement":1.8,"drive":"fwd","fuel_type":"gas","highway_mpg":26,"make":"kia","model":"sephia","transmission":"a","year":1995},{"city_mpg":21,"class":"compact car","combination_mpg":23,"cylinders":4,"displacement":1.8,"drive":"fwd","fuel_type":"gas","highway_mpg":26,"make":"kia","model":"sephia","transmission":"m","year":1995},{"city_mpg":17,"class":"special purpose vehicle","combination_mpg":19,"cylinders":4,"displacement":2,"drive":"rwd","fuel_type":"gas","highway_mpg":21,"make":"kia","model":"sportage 2wd","transmission":"m","year":1995},{"city_mpg":16,"class":"special purpose vehicle","combination_mpg":18,"cylinders":4,"displacement":2,"drive":"awd","fuel_type":"gas","highway_mpg":20,"make":"kia","model":"sportage 4wd","transmission":"a","year":1995},{"city_mpg":18,"class":"special purpose vehicle","combination_mpg":19,"cylinders":4,"displacement":2,"drive":"awd","fuel_type":"gas","highway_mpg":22,"make":"kia","model":"sportage 4wd","transmission":"m","year":1995}]let cars = [{"city_mpg":22,"class":"compact car","combination_mpg":24,"cylinders":4,"displacement":1.6,"drive":"fwd","fuel_type":"gas","highway_mpg":27,"make":"kia","model":"sephia","transmission":"a","year":1994},{"city_mpg":23,"class":"compact car","combination_mpg":26,"cylinders":4,"displacement":1.6,"drive":"fwd","fuel_type":"gas","highway_mpg":30,"make":"kia","model":"sephia","transmission":"m","year":1994},{"city_mpg":22,"class":"compact car","combination_mpg":25,"cylinders":4,"displacement":1.6,"drive":"fwd","fuel_type":"gas","highway_mpg":31,"make":"kia","model":"sephia","transmission":"a","year":1995},{"city_mpg":22,"class":"compact car","combination_mpg":25,"cylinders":4,"displacement":1.6,"drive":"fwd","fuel_type":"gas","highway_mpg":30,"make":"kia","model":"sephia","transmission":"m","year":1995},{"city_mpg":25,"class":"compact car","combination_mpg":28,"cylinders":4,"displacement":1.6,"drive":"fwd","fuel_type":"gas","highway_mpg":32,"make":"kia","model":"sephia","transmission":"m","year":1995},{"city_mpg":20,"class":"compact car","combination_mpg":22,"cylinders":4,"displacement":1.8,"drive":"fwd","fuel_type":"gas","highway_mpg":26,"make":"kia","model":"sephia","transmission":"a","year":1995},{"city_mpg":21,"class":"compact car","combination_mpg":23,"cylinders":4,"displacement":1.8,"drive":"fwd","fuel_type":"gas","highway_mpg":26,"make":"kia","model":"sephia","transmission":"m","year":1995},{"city_mpg":17,"class":"special purpose vehicle","combination_mpg":19,"cylinders":4,"displacement":2,"drive":"rwd","fuel_type":"gas","highway_mpg":21,"make":"kia","model":"sportage 2wd","transmission":"m","year":1995},{"city_mpg":16,"class":"special purpose vehicle","combination_mpg":18,"cylinders":4,"displacement":2,"drive":"awd","fuel_type":"gas","highway_mpg":20,"make":"kia","model":"sportage 4wd","transmission":"a","year":1995},{"city_mpg":18,"class":"special purpose vehicle","combination_mpg":19,"cylinders":4,"displacement":2,"drive":"awd","fuel_type":"gas","highway_mpg":22,"make":"kia","model":"sportage 4wd","transmission":"m","year":1995}]let cars = [{"city_mpg":22,"class":"compact car","combination_mpg":24,"cylinders":4,"displacement":1.6,"drive":"fwd","fuel_type":"gas","highway_mpg":27,"make":"kia","model":"sephia","transmission":"a","year":1994},{"city_mpg":23,"class":"compact car","combination_mpg":26,"cylinders":4,"displacement":1.6,"drive":"fwd","fuel_type":"gas","highway_mpg":30,"make":"kia","model":"sephia","transmission":"m","year":1994},{"city_mpg":22,"class":"compact car","combination_mpg":25,"cylinders":4,"displacement":1.6,"drive":"fwd","fuel_type":"gas","highway_mpg":31,"make":"kia","model":"sephia","transmission":"a","year":1995},{"city_mpg":22,"class":"compact car","combination_mpg":25,"cylinders":4,"displacement":1.6,"drive":"fwd","fuel_type":"gas","highway_mpg":30,"make":"kia","model":"sephia","transmission":"m","year":1995},{"city_mpg":25,"class":"compact car","combination_mpg":28,"cylinders":4,"displacement":1.6,"drive":"fwd","fuel_type":"gas","highway_mpg":32,"make":"kia","model":"sephia","transmission":"m","year":1995},{"city_mpg":20,"class":"compact car","combination_mpg":22,"cylinders":4,"displacement":1.8,"drive":"fwd","fuel_type":"gas","highway_mpg":26,"make":"kia","model":"sephia","transmission":"a","year":1995},{"city_mpg":21,"class":"compact car","combination_mpg":23,"cylinders":4,"displacement":1.8,"drive":"fwd","fuel_type":"gas","highway_mpg":26,"make":"kia","model":"sephia","transmission":"m","year":1995},{"city_mpg":17,"class":"special purpose vehicle","combination_mpg":19,"cylinders":4,"displacement":2,"drive":"rwd","fuel_type":"gas","highway_mpg":21,"make":"kia","model":"sportage 2wd","transmission":"m","year":1995},{"city_mpg":16,"class":"special purpose vehicle","combination_mpg":18,"cylinders":4,"displacement":2,"drive":"awd","fuel_type":"gas","highway_mpg":20,"make":"kia","model":"sportage 4wd","transmission":"a","year":1995},{"city_mpg":18,"class":"special purpose vehicle","combination_mpg":19,"cylinders":4,"displacement":2,"drive":"awd","fuel_type":"gas","highway_mpg":22,"make":"kia","model":"sportage 4wd","transmission":"m","year":1995}]let cars = [{"city_mpg":22,"class":"compact car","combination_mpg":24,"cylinders":4,"displacement":1.6,"drive":"fwd","fuel_type":"gas","highway_mpg":27,"make":"kia","model":"sephia","transmission":"a","year":1994},{"city_mpg":23,"class":"compact car","combination_mpg":26,"cylinders":4,"displacement":1.6,"drive":"fwd","fuel_type":"gas","highway_mpg":30,"make":"kia","model":"sephia","transmission":"m","year":1994},{"city_mpg":22,"class":"compact car","combination_mpg":25,"cylinders":4,"displacement":1.6,"drive":"fwd","fuel_type":"gas","highway_mpg":31,"make":"kia","model":"sephia","transmission":"a","year":1995},{"city_mpg":22,"class":"compact car","combination_mpg":25,"cylinders":4,"displacement":1.6,"drive":"fwd","fuel_type":"gas","highway_mpg":30,"make":"kia","model":"sephia","transmission":"m","year":1995},{"city_mpg":25,"class":"compact car","combination_mpg":28,"cylinders":4,"displacement":1.6,"drive":"fwd","fuel_type":"gas","highway_mpg":32,"make":"kia","model":"sephia","transmission":"m","year":1995},{"city_mpg":20,"class":"compact car","combination_mpg":22,"cylinders":4,"displacement":1.8,"drive":"fwd","fuel_type":"gas","highway_mpg":26,"make":"kia","model":"sephia","transmission":"a","year":1995},{"city_mpg":21,"class":"compact car","combination_mpg":23,"cylinders":4,"displacement":1.8,"drive":"fwd","fuel_type":"gas","highway_mpg":26,"make":"kia","model":"sephia","transmission":"m","year":1995},{"city_mpg":17,"class":"special purpose vehicle","combination_mpg":19,"cylinders":4,"displacement":2,"drive":"rwd","fuel_type":"gas","highway_mpg":21,"make":"kia","model":"sportage 2wd","transmission":"m","year":1995},{"city_mpg":16,"class":"special purpose vehicle","combination_mpg":18,"cylinders":4,"displacement":2,"drive":"awd","fuel_type":"gas","highway_mpg":20,"make":"kia","model":"sportage 4wd","transmission":"a","year":1995},{"city_mpg":18,"class":"special purpose vehicle","combination_mpg":19,"cylinders":4,"displacement":2,"drive":"awd","fuel_type":"gas","highway_mpg":22,"make":"kia","model":"sportage 4wd","transmission":"m","year":1995}]let cars = [{"city_mpg":22,"class":"compact car","combination_mpg":24,"cylinders":4,"displacement":1.6,"drive":"fwd","fuel_type":"gas","highway_mpg":27,"make":"kia","model":"sephia","transmission":"a","year":1994},{"city_mpg":23,"class":"compact car","combination_mpg":26,"cylinders":4,"displacement":1.6,"drive":"fwd","fuel_type":"gas","highway_mpg":30,"make":"kia","model":"sephia","transmission":"m","year":1994},{"city_mpg":22,"class":"compact car","combination_mpg":25,"cylinders":4,"displacement":1.6,"drive":"fwd","fuel_type":"gas","highway_mpg":31,"make":"kia","model":"sephia","transmission":"a","year":1995},{"city_mpg":22,"class":"compact car","combination_mpg":25,"cylinders":4,"displacement":1.6,"drive":"fwd","fuel_type":"gas","highway_mpg":30,"make":"kia","model":"sephia","transmission":"m","year":1995},{"city_mpg":25,"class":"compact car","combination_mpg":28,"cylinders":4,"displacement":1.6,"drive":"fwd","fuel_type":"gas","highway_mpg":32,"make":"kia","model":"sephia","transmission":"m","year":1995},{"city_mpg":20,"class":"compact car","combination_mpg":22,"cylinders":4,"displacement":1.8,"drive":"fwd","fuel_type":"gas","highway_mpg":26,"make":"kia","model":"sephia","transmission":"a","year":1995},{"city_mpg":21,"class":"compact car","combination_mpg":23,"cylinders":4,"displacement":1.8,"drive":"fwd","fuel_type":"gas","highway_mpg":26,"make":"kia","model":"sephia","transmission":"m","year":1995},{"city_mpg":17,"class":"special purpose vehicle","combination_mpg":19,"cylinders":4,"displacement":2,"drive":"rwd","fuel_type":"gas","highway_mpg":21,"make":"kia","model":"sportage 2wd","transmission":"m","year":1995},{"city_mpg":16,"class":"special purpose vehicle","combination_mpg":18,"cylinders":4,"displacement":2,"drive":"awd","fuel_type":"gas","highway_mpg":20,"make":"kia","model":"sportage 4wd","transmission":"a","year":1995},{"city_mpg":18,"class":"special purpose vehicle","combination_mpg":19,"cylinders":4,"displacement":2,"drive":"awd","fuel_type":"gas","highway_mpg":22,"make":"kia","model":"sportage 4wd","transmission":"m","year":1995}]